src/IRTS/SchemeRTS.hs: rts.scm
	echo 'module IRTS.SchemeRTS (schemeRTS) where' > $@
	echo 'import Data.Text as T' >> $@
	echo 'schemeRTS = T.unlines' >> $@
	echo '  [ "; generated by idris-scheme"' >> $@
	cat $< \
		| sed 's/"/\\"/g'   \
		| sed 's/^/  , "/' \
		| sed 's/$$/"/'    \
		>> $@; \
	echo '  ]' >> $@
