src/IRTS/SchemeRTS.hs: rts.scm
	echo 'module IRTS.SchemeRTS (schemeRTS) where' > $@
	echo 'import Data.Text as T' >> $@
	echo 'schemeRTS = T.unlines' >> $@
	echo '  [ "; generated by idris-scheme"' >> $@
	cat $< | while read line; do     \
		echo "  , \"$$line\"" >> $@; \
	done
	echo '  ]' >> $@
